export enum Permission {
  LEADS = "LEADS",
  BUDGET = "BUDGET",
  GROUPS = "GROUPS",
  TEACHERS = "TEACHERS",
  STUDENTS = "STUDENTS",
  PAYMENTS = "PAYMENTS",
  ATTENDANCE = "ATTENDANCE",
  NOTIFICATION = "NOTIFICATION",
}
